server:
  port: 8088
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/ProductDB
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  instance:
    statusPageUrlPath: ${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${management.endpoints.web.base-path}/health
    #prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8099/eureka/


